---
# SSH user (must have sudo access)
ansible_user: root

# Q1 application
q1_version: "0.1.0-SNAPSHOT"
q1_jar_local: "{{ playbook_dir }}/../q1-api/target/q1-api-{{ q1_version }}.jar"
q1_port: 9000
q1_data_dir: /var/lib/q1/data
q1_rf: 3

# etcd cluster endpoints used by q1 nodes
q1_etcd_endpoints: "{{ groups['etcd'] | map('regex_replace', '^(.*)$', 'http://\\1:2379') | join(',') }}"
